### ISSUE TITLE
 Output format: Which properties (if any) can be null omitted?

### ISSUE THREAD

**Issue by cmeeren** [editor-js/image#127]
For a valid image block, can any of the `file`, `caption`, `withBorder`, `withBackground`, or `stretched` properties under any circumstances (now or in the future) be `null` or omitted? For the `file` object, will the `url` always be non-null? Are any of the aforementioned properties guaranteed to always be present and non-`null` for this block to be valid?

Context: I'm a back-end .NET developer needing to parse Editor.js documents. The readme lists all of the aforementioned properties but does not explicitly guarantee that they will always be present and non-null. Back-end deserialization/parsing in strongly typed languages would be easier with some guarantees about which properties can and can not be null/omitted. (Ideally, any such guarantees should be added to the readme to ensure they are formalized and kept in the future.)

**Comment by cmeeren** [comment]
Could anyone clarify this, please? Thanks! 😊

**Comment by robonetphy** [comment]
@cmeeren Sorry for the late reply.
so here is the default value of the mentioned property.
| Field          | Type      | Description                     |
| -------------- | --------- | ------------------------------- |
| file           | `object`  | {} (empty object)|
| caption        | `string`  | "" (empty string)|
| withBorder     | `boolean` | false  |
| withBackground | `boolean` | false        |
| stretched      | `boolean` | false |

So from above, we can say that the property mentioned above can not be `null`. It is also due to various checks for `null` value 
 for these properties inside the plugin which if found then replace the corresponding default value.
If any such situation occurs when this property will be `null`. Please Let's know because that will be a bug 😄.

**Comment by cmeeren** [comment]
Thanks! Is it then possible (apart from bugs) that the `url` property of the `file` object is omitted, or will `file` always be set to a non-empty object? It seems intuitively weird if `file` can ever be set to an empty object without `url`.

**Comment by robonetphy** [comment]
Actually, the purpose of the `file` object is to store the response from the backend which should always contain `url` as property but if you want to store some useful data with it, you can.
So, you are right `file` object either contains the response of the endpoint (which must contain the `url` property for successful response) or a default value as an empty object.
you can check more detail about backend response formate [here](https://github.com/editor-js/image#backend-response-format-)

**Comment by robonetphy** [comment]
@cmeeren Let me know if you have any more doubt?

**Comment by cmeeren** [comment]
I'm good, thanks a lot for the clarifications!
