### ISSUE TITLE
Unable to upload image

### ISSUE THREAD

**Issue by AlexxMart** [editor-js/image#64]
The icon for the image appears just fine but I get a warning that the image cannot be uploaded. Right now I'm testing on a dev environment and cannot connect to a live server to upload the image.

The problem still happens when I don't pass a config object. Is there a way to test with mock endpoints that will work?

This is my current config for that tool:

```
image: {
          class: ImageTool,
          config: {
            endpoints: {
              byFile: "http://localhost:3000/uploadFile",
              byUrl: "http://localhost:3000/fetchUrl"
            }
          }
        }
```

and this is the error I get in the console.

```
body: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /uploadFile</pre>\n</body>\n</html>\n"

code: 404
connection: "keep-alive"
"content-length": "150"
"content-security-policy": "default-src 'none'"
"content-type": "text/html; charset=utf-8"
date: "Thu, 27 Feb 2020 17:01:06 GMT"
vary: "Accept-Encoding"
"x-content-type-options": "nosniff"
"x-powered-by": "Express"
```

**Comment by mikekoro** [comment]
You need to write & run your own server to handle those file uploads. `http://localhost:3000/uploadFile` is just an exmaple.

**Comment by laurentP13** [comment]
@mikekoro is correct.  Just to be clear
- the image tool will POST the image data to the backend into the FILES dictionary of the HttpRequest,
- your backend must store the image somewhere (your choice)
- then the backend returns a dict with the url from where the fetch the image next time.
Hope this helps.
@AlexxMart If you think this is still an issue with the Image tool, pls comment, otherwise pls recommend closing it

**Comment by AlexxMart** [comment]
That solves my question, I though that the error I was getting was due to a bug in the Image plugin code.
